/*
 * Zhihu-Hyperion - Free & Ad-Free Zhihu client for all platforms.
 * Copyright (C) 2026, eltavine <me@eltavine.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation (version 3 only).
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// Generated by core/icons/symbols.py from symbols.txt; do not edit by hand.

package com.github.zly2006.zhihu.icons

import zhihu.core.icons.generated.resources.Res
import zhihu.core.icons.generated.resources.account_circle
import zhihu.core.icons.generated.resources.ad_off
import zhihu.core.icons.generated.resources.add
import zhihu.core.icons.generated.resources.add_comment
import zhihu.core.icons.generated.resources.add_reaction
import zhihu.core.icons.generated.resources.android
import zhihu.core.icons.generated.resources.archive
import zhihu.core.icons.generated.resources.arrow_back
import zhihu.core.icons.generated.resources.arrow_circle_up
import zhihu.core.icons.generated.resources.arrow_downward
import zhihu.core.icons.generated.resources.arrow_outward
import zhihu.core.icons.generated.resources.arrow_upward
import zhihu.core.icons.generated.resources.auto_awesome
import zhihu.core.icons.generated.resources.auto_stories
import zhihu.core.icons.generated.resources.autorenew
import zhihu.core.icons.generated.resources.bar_chart
import zhihu.core.icons.generated.resources.block
import zhihu.core.icons.generated.resources.bolt
import zhihu.core.icons.generated.resources.bookmark
import zhihu.core.icons.generated.resources.bookmark_filled
import zhihu.core.icons.generated.resources.bookmarks
import zhihu.core.icons.generated.resources.bookmarks_filled
import zhihu.core.icons.generated.resources.bottom_navigation
import zhihu.core.icons.generated.resources.brightness_auto
import zhihu.core.icons.generated.resources.calendar_today
import zhihu.core.icons.generated.resources.call_to_action
import zhihu.core.icons.generated.resources.category
import zhihu.core.icons.generated.resources.chat
import zhihu.core.icons.generated.resources.chat_bubble
import zhihu.core.icons.generated.resources.check
import zhihu.core.icons.generated.resources.check_circle
import zhihu.core.icons.generated.resources.close
import zhihu.core.icons.generated.resources.cloud_download
import zhihu.core.icons.generated.resources.cloud_sync
import zhihu.core.icons.generated.resources.cloud_upload
import zhihu.core.icons.generated.resources.code
import zhihu.core.icons.generated.resources.comment
import zhihu.core.icons.generated.resources.contact_page
import zhihu.core.icons.generated.resources.contact_support
import zhihu.core.icons.generated.resources.content_copy
import zhihu.core.icons.generated.resources.contrast
import zhihu.core.icons.generated.resources.cookie
import zhihu.core.icons.generated.resources.copy_all
import zhihu.core.icons.generated.resources.dark_mode
import zhihu.core.icons.generated.resources.data_object
import zhihu.core.icons.generated.resources.database
import zhihu.core.icons.generated.resources.date_range
import zhihu.core.icons.generated.resources.delete
import zhihu.core.icons.generated.resources.delete_sweep
import zhihu.core.icons.generated.resources.desktop_windows
import zhihu.core.icons.generated.resources.developer_mode
import zhihu.core.icons.generated.resources.dns
import zhihu.core.icons.generated.resources.done_all
import zhihu.core.icons.generated.resources.download
import zhihu.core.icons.generated.resources.edit
import zhihu.core.icons.generated.resources.error
import zhihu.core.icons.generated.resources.event
import zhihu.core.icons.generated.resources.expand_less
import zhihu.core.icons.generated.resources.expand_more
import zhihu.core.icons.generated.resources.explore
import zhihu.core.icons.generated.resources.favorite
import zhihu.core.icons.generated.resources.favorite_filled
import zhihu.core.icons.generated.resources.filter_alt
import zhihu.core.icons.generated.resources.filter_center_focus
import zhihu.core.icons.generated.resources.filter_list
import zhihu.core.icons.generated.resources.flag
import zhihu.core.icons.generated.resources.folder_open
import zhihu.core.icons.generated.resources.font_download
import zhihu.core.icons.generated.resources.format_align_justify
import zhihu.core.icons.generated.resources.format_color_fill
import zhihu.core.icons.generated.resources.format_line_spacing
import zhihu.core.icons.generated.resources.format_list_bulleted
import zhihu.core.icons.generated.resources.format_list_numbered
import zhihu.core.icons.generated.resources.format_paint
import zhihu.core.icons.generated.resources.format_paragraph
import zhihu.core.icons.generated.resources.format_size
import zhihu.core.icons.generated.resources.forum
import zhihu.core.icons.generated.resources.fullscreen
import zhihu.core.icons.generated.resources.function
import zhihu.core.icons.generated.resources.gavel
import zhihu.core.icons.generated.resources.graphic_eq
import zhihu.core.icons.generated.resources.group
import zhihu.core.icons.generated.resources.group_filled
import zhihu.core.icons.generated.resources.groups
import zhihu.core.icons.generated.resources.headphones
import zhihu.core.icons.generated.resources.height
import zhihu.core.icons.generated.resources.help
import zhihu.core.icons.generated.resources.high_quality
import zhihu.core.icons.generated.resources.history
import zhihu.core.icons.generated.resources.history_filled
import zhihu.core.icons.generated.resources.home
import zhihu.core.icons.generated.resources.home_filled
import zhihu.core.icons.generated.resources.horizontal_rule
import zhihu.core.icons.generated.resources.hourglass_top
import zhihu.core.icons.generated.resources.how_to_reg
import zhihu.core.icons.generated.resources.html
import zhihu.core.icons.generated.resources.image
import zhihu.core.icons.generated.resources.info
import zhihu.core.icons.generated.resources.instant_mix
import zhihu.core.icons.generated.resources.keyboard
import zhihu.core.icons.generated.resources.keyboard_arrow_down
import zhihu.core.icons.generated.resources.keyboard_arrow_right
import zhihu.core.icons.generated.resources.keyboard_arrow_up
import zhihu.core.icons.generated.resources.keyboard_double_arrow_down
import zhihu.core.icons.generated.resources.language
import zhihu.core.icons.generated.resources.last_page
import zhihu.core.icons.generated.resources.license
import zhihu.core.icons.generated.resources.light_mode
import zhihu.core.icons.generated.resources.linear_scale
import zhihu.core.icons.generated.resources.link_off
import zhihu.core.icons.generated.resources.lock
import zhihu.core.icons.generated.resources.lock_open
import zhihu.core.icons.generated.resources.login
import zhihu.core.icons.generated.resources.logout
import zhihu.core.icons.generated.resources.manage_accounts
import zhihu.core.icons.generated.resources.manage_accounts_filled
import zhihu.core.icons.generated.resources.manage_history
import zhihu.core.icons.generated.resources.mark_chat_read
import zhihu.core.icons.generated.resources.match_word
import zhihu.core.icons.generated.resources.memory
import zhihu.core.icons.generated.resources.merge
import zhihu.core.icons.generated.resources.mood
import zhihu.core.icons.generated.resources.more_vert
import zhihu.core.icons.generated.resources.navigation
import zhihu.core.icons.generated.resources.network_check
import zhihu.core.icons.generated.resources.newspaper
import zhihu.core.icons.generated.resources.newspaper_filled
import zhihu.core.icons.generated.resources.notifications
import zhihu.core.icons.generated.resources.notifications_unread
import zhihu.core.icons.generated.resources.opacity
import zhihu.core.icons.generated.resources.open_in_browser
import zhihu.core.icons.generated.resources.open_in_new
import zhihu.core.icons.generated.resources.paid
import zhihu.core.icons.generated.resources.palette
import zhihu.core.icons.generated.resources.pause_circle_filled
import zhihu.core.icons.generated.resources.pause_filled
import zhihu.core.icons.generated.resources.person
import zhihu.core.icons.generated.resources.person_add
import zhihu.core.icons.generated.resources.person_off
import zhihu.core.icons.generated.resources.person_remove
import zhihu.core.icons.generated.resources.photo_camera
import zhihu.core.icons.generated.resources.picture_as_pdf
import zhihu.core.icons.generated.resources.play_arrow_filled
import zhihu.core.icons.generated.resources.playlist_remove
import zhihu.core.icons.generated.resources.power_settings_new
import zhihu.core.icons.generated.resources.psychology
import zhihu.core.icons.generated.resources.qr_code_scanner
import zhihu.core.icons.generated.resources.queue_music
import zhihu.core.icons.generated.resources.record_voice_over
import zhihu.core.icons.generated.resources.refresh
import zhihu.core.icons.generated.resources.reply
import zhihu.core.icons.generated.resources.rocket_launch
import zhihu.core.icons.generated.resources.rounded_corner
import zhihu.core.icons.generated.resources.save
import zhihu.core.icons.generated.resources.schedule
import zhihu.core.icons.generated.resources.school
import zhihu.core.icons.generated.resources.science
import zhihu.core.icons.generated.resources.search
import zhihu.core.icons.generated.resources.send
import zhihu.core.icons.generated.resources.sentiment_satisfied
import zhihu.core.icons.generated.resources.settings
import zhihu.core.icons.generated.resources.share
import zhihu.core.icons.generated.resources.short_text
import zhihu.core.icons.generated.resources.shuffle
import zhihu.core.icons.generated.resources.skip_next_filled
import zhihu.core.icons.generated.resources.skip_previous_filled
import zhihu.core.icons.generated.resources.smart_button
import zhihu.core.icons.generated.resources.smart_toy
import zhihu.core.icons.generated.resources.smartphone
import zhihu.core.icons.generated.resources.sms
import zhihu.core.icons.generated.resources.sort
import zhihu.core.icons.generated.resources.speed
import zhihu.core.icons.generated.resources.stop_filled
import zhihu.core.icons.generated.resources.style
import zhihu.core.icons.generated.resources.subject
import zhihu.core.icons.generated.resources.swap_horiz
import zhihu.core.icons.generated.resources.swap_vert
import zhihu.core.icons.generated.resources.swipe
import zhihu.core.icons.generated.resources.swipe_left
import zhihu.core.icons.generated.resources.swipe_vertical
import zhihu.core.icons.generated.resources.switch_account
import zhihu.core.icons.generated.resources.tag
import zhihu.core.icons.generated.resources.text_increase
import zhihu.core.icons.generated.resources.text_snippet
import zhihu.core.icons.generated.resources.thumb_up
import zhihu.core.icons.generated.resources.thumb_up_filled
import zhihu.core.icons.generated.resources.timer
import zhihu.core.icons.generated.resources.title
import zhihu.core.icons.generated.resources.toc
import zhihu.core.icons.generated.resources.touch_app
import zhihu.core.icons.generated.resources.tune
import zhihu.core.icons.generated.resources.vertical_align_top
import zhihu.core.icons.generated.resources.vertical_split
import zhihu.core.icons.generated.resources.view_agenda
import zhihu.core.icons.generated.resources.view_day
import zhihu.core.icons.generated.resources.view_headline
import zhihu.core.icons.generated.resources.view_quilt
import zhihu.core.icons.generated.resources.visibility
import zhihu.core.icons.generated.resources.visibility_off
import zhihu.core.icons.generated.resources.volume_off
import zhihu.core.icons.generated.resources.volume_up
import zhihu.core.icons.generated.resources.wallpaper
import zhihu.core.icons.generated.resources.web
import zhihu.core.icons.generated.resources.web_asset
import zhihu.core.icons.generated.resources.whatshot
import zhihu.core.icons.generated.resources.whatshot_filled

/**
 * 应用用到的全部图标，来自 Material Symbols Rounded。`*Filled` 是选中、已点赞、已收藏等状态用的填充版本。
 * 新增图标先在 core/icons/symbols.txt 登记，再运行 core/icons/symbols.py。
 */
object AppIcons {
    val AccountCircle = AppIcon(Res.drawable.account_circle)
    val AdOff = AppIcon(Res.drawable.ad_off)
    val Add = AppIcon(Res.drawable.add)
    val AddComment = AppIcon(Res.drawable.add_comment)
    val AddReaction = AppIcon(Res.drawable.add_reaction)
    val Android = AppIcon(Res.drawable.android)
    val Archive = AppIcon(Res.drawable.archive)
    val ArrowBack = AppIcon(Res.drawable.arrow_back)
    val ArrowCircleUp = AppIcon(Res.drawable.arrow_circle_up)
    val ArrowDownward = AppIcon(Res.drawable.arrow_downward)
    val ArrowOutward = AppIcon(Res.drawable.arrow_outward)
    val ArrowUpward = AppIcon(Res.drawable.arrow_upward)
    val AutoAwesome = AppIcon(Res.drawable.auto_awesome)
    val AutoStories = AppIcon(Res.drawable.auto_stories)
    val Autorenew = AppIcon(Res.drawable.autorenew)
    val BarChart = AppIcon(Res.drawable.bar_chart)
    val Block = AppIcon(Res.drawable.block)
    val Bolt = AppIcon(Res.drawable.bolt)
    val Bookmark = AppIcon(Res.drawable.bookmark)
    val BookmarkFilled = AppIcon(Res.drawable.bookmark_filled)
    val Bookmarks = AppIcon(Res.drawable.bookmarks)
    val BookmarksFilled = AppIcon(Res.drawable.bookmarks_filled)
    val BottomNavigation = AppIcon(Res.drawable.bottom_navigation)
    val BrightnessAuto = AppIcon(Res.drawable.brightness_auto)
    val CalendarToday = AppIcon(Res.drawable.calendar_today)
    val CallToAction = AppIcon(Res.drawable.call_to_action)
    val Category = AppIcon(Res.drawable.category)
    val Chat = AppIcon(Res.drawable.chat)
    val ChatBubble = AppIcon(Res.drawable.chat_bubble)
    val Check = AppIcon(Res.drawable.check)
    val CheckCircle = AppIcon(Res.drawable.check_circle)
    val Close = AppIcon(Res.drawable.close)
    val CloudDownload = AppIcon(Res.drawable.cloud_download)
    val CloudSync = AppIcon(Res.drawable.cloud_sync)
    val CloudUpload = AppIcon(Res.drawable.cloud_upload)
    val Code = AppIcon(Res.drawable.code)
    val Comment = AppIcon(Res.drawable.comment)
    val ContactPage = AppIcon(Res.drawable.contact_page)
    val ContactSupport = AppIcon(Res.drawable.contact_support)
    val ContentCopy = AppIcon(Res.drawable.content_copy)
    val Contrast = AppIcon(Res.drawable.contrast)
    val Cookie = AppIcon(Res.drawable.cookie)
    val CopyAll = AppIcon(Res.drawable.copy_all)
    val DarkMode = AppIcon(Res.drawable.dark_mode)
    val DataObject = AppIcon(Res.drawable.data_object)
    val Database = AppIcon(Res.drawable.database)
    val DateRange = AppIcon(Res.drawable.date_range)
    val Delete = AppIcon(Res.drawable.delete)
    val DeleteSweep = AppIcon(Res.drawable.delete_sweep)
    val DesktopWindows = AppIcon(Res.drawable.desktop_windows)
    val DeveloperMode = AppIcon(Res.drawable.developer_mode)
    val Dns = AppIcon(Res.drawable.dns)
    val DoneAll = AppIcon(Res.drawable.done_all)
    val Download = AppIcon(Res.drawable.download)
    val Edit = AppIcon(Res.drawable.edit)
    val Error = AppIcon(Res.drawable.error)
    val Event = AppIcon(Res.drawable.event)
    val ExpandLess = AppIcon(Res.drawable.expand_less)
    val ExpandMore = AppIcon(Res.drawable.expand_more)
    val Explore = AppIcon(Res.drawable.explore)
    val Favorite = AppIcon(Res.drawable.favorite)
    val FavoriteFilled = AppIcon(Res.drawable.favorite_filled)
    val FilterAlt = AppIcon(Res.drawable.filter_alt)
    val FilterCenterFocus = AppIcon(Res.drawable.filter_center_focus)
    val FilterList = AppIcon(Res.drawable.filter_list)
    val Flag = AppIcon(Res.drawable.flag)
    val FolderOpen = AppIcon(Res.drawable.folder_open)
    val FontDownload = AppIcon(Res.drawable.font_download)
    val FormatAlignJustify = AppIcon(Res.drawable.format_align_justify)
    val FormatColorFill = AppIcon(Res.drawable.format_color_fill)
    val FormatLineSpacing = AppIcon(Res.drawable.format_line_spacing)
    val FormatListBulleted = AppIcon(Res.drawable.format_list_bulleted)
    val FormatListNumbered = AppIcon(Res.drawable.format_list_numbered)
    val FormatPaint = AppIcon(Res.drawable.format_paint)
    val FormatParagraph = AppIcon(Res.drawable.format_paragraph)
    val FormatSize = AppIcon(Res.drawable.format_size)
    val Forum = AppIcon(Res.drawable.forum)
    val Fullscreen = AppIcon(Res.drawable.fullscreen)
    val Function = AppIcon(Res.drawable.function)
    val Gavel = AppIcon(Res.drawable.gavel)
    val GraphicEq = AppIcon(Res.drawable.graphic_eq)
    val Group = AppIcon(Res.drawable.group)
    val GroupFilled = AppIcon(Res.drawable.group_filled)
    val Groups = AppIcon(Res.drawable.groups)
    val Headphones = AppIcon(Res.drawable.headphones)
    val Height = AppIcon(Res.drawable.height)
    val Help = AppIcon(Res.drawable.help)
    val HighQuality = AppIcon(Res.drawable.high_quality)
    val History = AppIcon(Res.drawable.history)
    val HistoryFilled = AppIcon(Res.drawable.history_filled)
    val Home = AppIcon(Res.drawable.home)
    val HomeFilled = AppIcon(Res.drawable.home_filled)
    val HorizontalRule = AppIcon(Res.drawable.horizontal_rule)
    val HourglassTop = AppIcon(Res.drawable.hourglass_top)
    val HowToReg = AppIcon(Res.drawable.how_to_reg)
    val Html = AppIcon(Res.drawable.html)
    val Image = AppIcon(Res.drawable.image)
    val Info = AppIcon(Res.drawable.info)
    val InstantMix = AppIcon(Res.drawable.instant_mix)
    val Keyboard = AppIcon(Res.drawable.keyboard)
    val KeyboardArrowDown = AppIcon(Res.drawable.keyboard_arrow_down)
    val KeyboardArrowRight = AppIcon(Res.drawable.keyboard_arrow_right)
    val KeyboardArrowUp = AppIcon(Res.drawable.keyboard_arrow_up)
    val KeyboardDoubleArrowDown = AppIcon(Res.drawable.keyboard_double_arrow_down)
    val Language = AppIcon(Res.drawable.language)
    val LastPage = AppIcon(Res.drawable.last_page)
    val License = AppIcon(Res.drawable.license)
    val LightMode = AppIcon(Res.drawable.light_mode)
    val LinearScale = AppIcon(Res.drawable.linear_scale)
    val LinkOff = AppIcon(Res.drawable.link_off)
    val Lock = AppIcon(Res.drawable.lock)
    val LockOpen = AppIcon(Res.drawable.lock_open)
    val Login = AppIcon(Res.drawable.login)
    val Logout = AppIcon(Res.drawable.logout)
    val ManageAccounts = AppIcon(Res.drawable.manage_accounts)
    val ManageAccountsFilled = AppIcon(Res.drawable.manage_accounts_filled)
    val ManageHistory = AppIcon(Res.drawable.manage_history)
    val MarkChatRead = AppIcon(Res.drawable.mark_chat_read)
    val MatchWord = AppIcon(Res.drawable.match_word)
    val Memory = AppIcon(Res.drawable.memory)
    val Merge = AppIcon(Res.drawable.merge)
    val Mood = AppIcon(Res.drawable.mood)
    val MoreVert = AppIcon(Res.drawable.more_vert)
    val Navigation = AppIcon(Res.drawable.navigation)
    val NetworkCheck = AppIcon(Res.drawable.network_check)
    val Newspaper = AppIcon(Res.drawable.newspaper)
    val NewspaperFilled = AppIcon(Res.drawable.newspaper_filled)
    val Notifications = AppIcon(Res.drawable.notifications)
    val NotificationsUnread = AppIcon(Res.drawable.notifications_unread)
    val Opacity = AppIcon(Res.drawable.opacity)
    val OpenInBrowser = AppIcon(Res.drawable.open_in_browser)
    val OpenInNew = AppIcon(Res.drawable.open_in_new)
    val Paid = AppIcon(Res.drawable.paid)
    val Palette = AppIcon(Res.drawable.palette)
    val Pause = AppIcon(Res.drawable.pause_filled)
    val PauseCircle = AppIcon(Res.drawable.pause_circle_filled)
    val Person = AppIcon(Res.drawable.person)
    val PersonAdd = AppIcon(Res.drawable.person_add)
    val PersonOff = AppIcon(Res.drawable.person_off)
    val PersonRemove = AppIcon(Res.drawable.person_remove)
    val PhotoCamera = AppIcon(Res.drawable.photo_camera)
    val PictureAsPdf = AppIcon(Res.drawable.picture_as_pdf)
    val PlayArrow = AppIcon(Res.drawable.play_arrow_filled)
    val PlaylistRemove = AppIcon(Res.drawable.playlist_remove)
    val PowerSettingsNew = AppIcon(Res.drawable.power_settings_new)
    val Psychology = AppIcon(Res.drawable.psychology)
    val QrCodeScanner = AppIcon(Res.drawable.qr_code_scanner)
    val QueueMusic = AppIcon(Res.drawable.queue_music)
    val RecordVoiceOver = AppIcon(Res.drawable.record_voice_over)
    val Refresh = AppIcon(Res.drawable.refresh)
    val Reply = AppIcon(Res.drawable.reply)
    val RocketLaunch = AppIcon(Res.drawable.rocket_launch)
    val RoundedCorner = AppIcon(Res.drawable.rounded_corner)
    val Save = AppIcon(Res.drawable.save)
    val Schedule = AppIcon(Res.drawable.schedule)
    val School = AppIcon(Res.drawable.school)
    val Science = AppIcon(Res.drawable.science)
    val Search = AppIcon(Res.drawable.search)
    val Send = AppIcon(Res.drawable.send)
    val SentimentSatisfied = AppIcon(Res.drawable.sentiment_satisfied)
    val Settings = AppIcon(Res.drawable.settings)
    val Share = AppIcon(Res.drawable.share)
    val ShortText = AppIcon(Res.drawable.short_text)
    val Shuffle = AppIcon(Res.drawable.shuffle)
    val SkipNext = AppIcon(Res.drawable.skip_next_filled)
    val SkipPrevious = AppIcon(Res.drawable.skip_previous_filled)
    val SmartButton = AppIcon(Res.drawable.smart_button)
    val SmartToy = AppIcon(Res.drawable.smart_toy)
    val Smartphone = AppIcon(Res.drawable.smartphone)
    val Sms = AppIcon(Res.drawable.sms)
    val Sort = AppIcon(Res.drawable.sort)
    val Speed = AppIcon(Res.drawable.speed)
    val Stop = AppIcon(Res.drawable.stop_filled)
    val Style = AppIcon(Res.drawable.style)
    val Subject = AppIcon(Res.drawable.subject)
    val SwapHoriz = AppIcon(Res.drawable.swap_horiz)
    val SwapVert = AppIcon(Res.drawable.swap_vert)
    val Swipe = AppIcon(Res.drawable.swipe)
    val SwipeLeft = AppIcon(Res.drawable.swipe_left)
    val SwipeVertical = AppIcon(Res.drawable.swipe_vertical)
    val SwitchAccount = AppIcon(Res.drawable.switch_account)
    val Tag = AppIcon(Res.drawable.tag)
    val TextIncrease = AppIcon(Res.drawable.text_increase)
    val TextSnippet = AppIcon(Res.drawable.text_snippet)
    val ThumbUp = AppIcon(Res.drawable.thumb_up)
    val ThumbUpFilled = AppIcon(Res.drawable.thumb_up_filled)
    val Timer = AppIcon(Res.drawable.timer)
    val Title = AppIcon(Res.drawable.title)
    val Toc = AppIcon(Res.drawable.toc)
    val TouchApp = AppIcon(Res.drawable.touch_app)
    val Tune = AppIcon(Res.drawable.tune)
    val VerticalAlignTop = AppIcon(Res.drawable.vertical_align_top)
    val VerticalSplit = AppIcon(Res.drawable.vertical_split)
    val ViewAgenda = AppIcon(Res.drawable.view_agenda)
    val ViewDay = AppIcon(Res.drawable.view_day)
    val ViewHeadline = AppIcon(Res.drawable.view_headline)
    val ViewQuilt = AppIcon(Res.drawable.view_quilt)
    val Visibility = AppIcon(Res.drawable.visibility)
    val VisibilityOff = AppIcon(Res.drawable.visibility_off)
    val VolumeOff = AppIcon(Res.drawable.volume_off)
    val VolumeUp = AppIcon(Res.drawable.volume_up)
    val Wallpaper = AppIcon(Res.drawable.wallpaper)
    val Web = AppIcon(Res.drawable.web)
    val WebAsset = AppIcon(Res.drawable.web_asset)
    val Whatshot = AppIcon(Res.drawable.whatshot)
    val WhatshotFilled = AppIcon(Res.drawable.whatshot_filled)
}
