/*
 * Zhihu-Hyperion - Free & Ad-Free Zhihu client for all platforms.
 * Copyright (C) 2026, eltavine <me@eltavine.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation (version 3 only).
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// Generated by core/icons/symbols.py from symbols.txt; do not edit by hand.

package com.github.zly2006.zhihu.icons

import zhihu.core.icons.generated.resources.Res
import zhihu.core.icons.generated.resources.account_circle
import zhihu.core.icons.generated.resources.add
import zhihu.core.icons.generated.resources.archive
import zhihu.core.icons.generated.resources.arrow_back
import zhihu.core.icons.generated.resources.arrow_circle_up
import zhihu.core.icons.generated.resources.arrow_downward
import zhihu.core.icons.generated.resources.arrow_forward
import zhihu.core.icons.generated.resources.arrow_outward
import zhihu.core.icons.generated.resources.arrow_upward
import zhihu.core.icons.generated.resources.bookmark
import zhihu.core.icons.generated.resources.bookmark_filled
import zhihu.core.icons.generated.resources.bookmarks
import zhihu.core.icons.generated.resources.bookmarks_filled
import zhihu.core.icons.generated.resources.chat_bubble
import zhihu.core.icons.generated.resources.check
import zhihu.core.icons.generated.resources.close
import zhihu.core.icons.generated.resources.cloud_download
import zhihu.core.icons.generated.resources.cloud_sync
import zhihu.core.icons.generated.resources.cloud_upload
import zhihu.core.icons.generated.resources.code
import zhihu.core.icons.generated.resources.comment
import zhihu.core.icons.generated.resources.contact_page
import zhihu.core.icons.generated.resources.content_copy
import zhihu.core.icons.generated.resources.copy_all
import zhihu.core.icons.generated.resources.data_object
import zhihu.core.icons.generated.resources.date_range
import zhihu.core.icons.generated.resources.delete
import zhihu.core.icons.generated.resources.desktop_windows
import zhihu.core.icons.generated.resources.download
import zhihu.core.icons.generated.resources.edit
import zhihu.core.icons.generated.resources.error
import zhihu.core.icons.generated.resources.expand_less
import zhihu.core.icons.generated.resources.expand_more
import zhihu.core.icons.generated.resources.favorite
import zhihu.core.icons.generated.resources.favorite_filled
import zhihu.core.icons.generated.resources.filter_alt
import zhihu.core.icons.generated.resources.filter_center_focus
import zhihu.core.icons.generated.resources.filter_list
import zhihu.core.icons.generated.resources.flag
import zhihu.core.icons.generated.resources.folder
import zhihu.core.icons.generated.resources.folder_open
import zhihu.core.icons.generated.resources.format_list_bulleted
import zhihu.core.icons.generated.resources.graphic_eq
import zhihu.core.icons.generated.resources.group
import zhihu.core.icons.generated.resources.group_filled
import zhihu.core.icons.generated.resources.groups
import zhihu.core.icons.generated.resources.headphones
import zhihu.core.icons.generated.resources.help
import zhihu.core.icons.generated.resources.history
import zhihu.core.icons.generated.resources.history_filled
import zhihu.core.icons.generated.resources.home
import zhihu.core.icons.generated.resources.home_filled
import zhihu.core.icons.generated.resources.image
import zhihu.core.icons.generated.resources.info
import zhihu.core.icons.generated.resources.keyboard
import zhihu.core.icons.generated.resources.keyboard_arrow_down
import zhihu.core.icons.generated.resources.keyboard_arrow_right
import zhihu.core.icons.generated.resources.keyboard_arrow_up
import zhihu.core.icons.generated.resources.lock
import zhihu.core.icons.generated.resources.lock_open
import zhihu.core.icons.generated.resources.login
import zhihu.core.icons.generated.resources.logout
import zhihu.core.icons.generated.resources.manage_accounts
import zhihu.core.icons.generated.resources.manage_accounts_filled
import zhihu.core.icons.generated.resources.mark_chat_read
import zhihu.core.icons.generated.resources.mark_unread_chat_alt
import zhihu.core.icons.generated.resources.memory
import zhihu.core.icons.generated.resources.mood
import zhihu.core.icons.generated.resources.more_vert
import zhihu.core.icons.generated.resources.network_check
import zhihu.core.icons.generated.resources.newspaper
import zhihu.core.icons.generated.resources.newspaper_filled
import zhihu.core.icons.generated.resources.notifications
import zhihu.core.icons.generated.resources.palette
import zhihu.core.icons.generated.resources.pause_circle_filled
import zhihu.core.icons.generated.resources.pause_filled
import zhihu.core.icons.generated.resources.person_add
import zhihu.core.icons.generated.resources.photo_camera
import zhihu.core.icons.generated.resources.picture_as_pdf
import zhihu.core.icons.generated.resources.play_arrow_filled
import zhihu.core.icons.generated.resources.qr_code_scanner
import zhihu.core.icons.generated.resources.queue_music
import zhihu.core.icons.generated.resources.refresh
import zhihu.core.icons.generated.resources.reply
import zhihu.core.icons.generated.resources.save
import zhihu.core.icons.generated.resources.schedule
import zhihu.core.icons.generated.resources.search
import zhihu.core.icons.generated.resources.send
import zhihu.core.icons.generated.resources.sentiment_satisfied
import zhihu.core.icons.generated.resources.settings
import zhihu.core.icons.generated.resources.share
import zhihu.core.icons.generated.resources.shuffle
import zhihu.core.icons.generated.resources.skip_next_filled
import zhihu.core.icons.generated.resources.skip_previous_filled
import zhihu.core.icons.generated.resources.speed
import zhihu.core.icons.generated.resources.stop_filled
import zhihu.core.icons.generated.resources.switch_account
import zhihu.core.icons.generated.resources.tag
import zhihu.core.icons.generated.resources.thumb_up
import zhihu.core.icons.generated.resources.thumb_up_filled
import zhihu.core.icons.generated.resources.visibility
import zhihu.core.icons.generated.resources.visibility_off
import zhihu.core.icons.generated.resources.volume_off
import zhihu.core.icons.generated.resources.volume_up
import zhihu.core.icons.generated.resources.whatshot
import zhihu.core.icons.generated.resources.whatshot_filled

/**
 * 应用用到的全部图标，来自 Material Symbols Rounded。`*Filled` 是选中、已点赞、已收藏等状态用的填充版本。
 * 新增图标先在 core/icons/symbols.txt 登记，再运行 core/icons/symbols.py。
 */
object AppIcons {
    val AccountCircle = AppIcon(Res.drawable.account_circle)
    val Add = AppIcon(Res.drawable.add)
    val Archive = AppIcon(Res.drawable.archive)
    val ArrowBack = AppIcon(Res.drawable.arrow_back)
    val ArrowCircleUp = AppIcon(Res.drawable.arrow_circle_up)
    val ArrowDownward = AppIcon(Res.drawable.arrow_downward)
    val ArrowForward = AppIcon(Res.drawable.arrow_forward)
    val ArrowOutward = AppIcon(Res.drawable.arrow_outward)
    val ArrowUpward = AppIcon(Res.drawable.arrow_upward)
    val Bookmark = AppIcon(Res.drawable.bookmark)
    val BookmarkFilled = AppIcon(Res.drawable.bookmark_filled)
    val Bookmarks = AppIcon(Res.drawable.bookmarks)
    val BookmarksFilled = AppIcon(Res.drawable.bookmarks_filled)
    val ChatBubble = AppIcon(Res.drawable.chat_bubble)
    val Check = AppIcon(Res.drawable.check)
    val Close = AppIcon(Res.drawable.close)
    val CloudDownload = AppIcon(Res.drawable.cloud_download)
    val CloudSync = AppIcon(Res.drawable.cloud_sync)
    val CloudUpload = AppIcon(Res.drawable.cloud_upload)
    val Code = AppIcon(Res.drawable.code)
    val Comment = AppIcon(Res.drawable.comment)
    val ContactPage = AppIcon(Res.drawable.contact_page)
    val ContentCopy = AppIcon(Res.drawable.content_copy)
    val CopyAll = AppIcon(Res.drawable.copy_all)
    val DataObject = AppIcon(Res.drawable.data_object)
    val DateRange = AppIcon(Res.drawable.date_range)
    val Delete = AppIcon(Res.drawable.delete)
    val DesktopWindows = AppIcon(Res.drawable.desktop_windows)
    val Download = AppIcon(Res.drawable.download)
    val Edit = AppIcon(Res.drawable.edit)
    val Error = AppIcon(Res.drawable.error)
    val ExpandLess = AppIcon(Res.drawable.expand_less)
    val ExpandMore = AppIcon(Res.drawable.expand_more)
    val Favorite = AppIcon(Res.drawable.favorite)
    val FavoriteFilled = AppIcon(Res.drawable.favorite_filled)
    val FilterAlt = AppIcon(Res.drawable.filter_alt)
    val FilterCenterFocus = AppIcon(Res.drawable.filter_center_focus)
    val FilterList = AppIcon(Res.drawable.filter_list)
    val Flag = AppIcon(Res.drawable.flag)
    val Folder = AppIcon(Res.drawable.folder)
    val FolderOpen = AppIcon(Res.drawable.folder_open)
    val FormatListBulleted = AppIcon(Res.drawable.format_list_bulleted)
    val GraphicEq = AppIcon(Res.drawable.graphic_eq)
    val Group = AppIcon(Res.drawable.group)
    val GroupFilled = AppIcon(Res.drawable.group_filled)
    val Groups = AppIcon(Res.drawable.groups)
    val Headphones = AppIcon(Res.drawable.headphones)
    val Help = AppIcon(Res.drawable.help)
    val History = AppIcon(Res.drawable.history)
    val HistoryFilled = AppIcon(Res.drawable.history_filled)
    val Home = AppIcon(Res.drawable.home)
    val HomeFilled = AppIcon(Res.drawable.home_filled)
    val Image = AppIcon(Res.drawable.image)
    val Info = AppIcon(Res.drawable.info)
    val Keyboard = AppIcon(Res.drawable.keyboard)
    val KeyboardArrowDown = AppIcon(Res.drawable.keyboard_arrow_down)
    val KeyboardArrowRight = AppIcon(Res.drawable.keyboard_arrow_right)
    val KeyboardArrowUp = AppIcon(Res.drawable.keyboard_arrow_up)
    val Lock = AppIcon(Res.drawable.lock)
    val LockOpen = AppIcon(Res.drawable.lock_open)
    val Login = AppIcon(Res.drawable.login)
    val Logout = AppIcon(Res.drawable.logout)
    val ManageAccounts = AppIcon(Res.drawable.manage_accounts)
    val ManageAccountsFilled = AppIcon(Res.drawable.manage_accounts_filled)
    val MarkChatRead = AppIcon(Res.drawable.mark_chat_read)
    val MarkUnreadChatAlt = AppIcon(Res.drawable.mark_unread_chat_alt)
    val Memory = AppIcon(Res.drawable.memory)
    val Mood = AppIcon(Res.drawable.mood)
    val MoreVert = AppIcon(Res.drawable.more_vert)
    val NetworkCheck = AppIcon(Res.drawable.network_check)
    val Newspaper = AppIcon(Res.drawable.newspaper)
    val NewspaperFilled = AppIcon(Res.drawable.newspaper_filled)
    val Notifications = AppIcon(Res.drawable.notifications)
    val Palette = AppIcon(Res.drawable.palette)
    val Pause = AppIcon(Res.drawable.pause_filled)
    val PauseCircle = AppIcon(Res.drawable.pause_circle_filled)
    val PersonAdd = AppIcon(Res.drawable.person_add)
    val PhotoCamera = AppIcon(Res.drawable.photo_camera)
    val PictureAsPdf = AppIcon(Res.drawable.picture_as_pdf)
    val PlayArrow = AppIcon(Res.drawable.play_arrow_filled)
    val QrCodeScanner = AppIcon(Res.drawable.qr_code_scanner)
    val QueueMusic = AppIcon(Res.drawable.queue_music)
    val Refresh = AppIcon(Res.drawable.refresh)
    val Reply = AppIcon(Res.drawable.reply)
    val Save = AppIcon(Res.drawable.save)
    val Schedule = AppIcon(Res.drawable.schedule)
    val Search = AppIcon(Res.drawable.search)
    val Send = AppIcon(Res.drawable.send)
    val SentimentSatisfied = AppIcon(Res.drawable.sentiment_satisfied)
    val Settings = AppIcon(Res.drawable.settings)
    val Share = AppIcon(Res.drawable.share)
    val Shuffle = AppIcon(Res.drawable.shuffle)
    val SkipNext = AppIcon(Res.drawable.skip_next_filled)
    val SkipPrevious = AppIcon(Res.drawable.skip_previous_filled)
    val Speed = AppIcon(Res.drawable.speed)
    val Stop = AppIcon(Res.drawable.stop_filled)
    val SwitchAccount = AppIcon(Res.drawable.switch_account)
    val Tag = AppIcon(Res.drawable.tag)
    val ThumbUp = AppIcon(Res.drawable.thumb_up)
    val ThumbUpFilled = AppIcon(Res.drawable.thumb_up_filled)
    val Visibility = AppIcon(Res.drawable.visibility)
    val VisibilityOff = AppIcon(Res.drawable.visibility_off)
    val VolumeOff = AppIcon(Res.drawable.volume_off)
    val VolumeUp = AppIcon(Res.drawable.volume_up)
    val Whatshot = AppIcon(Res.drawable.whatshot)
    val WhatshotFilled = AppIcon(Res.drawable.whatshot_filled)
}
