#!/usr/bin/env python3
# Zhihu-Hyperion - Free & Ad-Free Zhihu client for all platforms.
# Copyright (C) 2026, eltavine <me@eltavine.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation (version 3 only).
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""Keeps the author lines of the license headers in step with git history.

A file eltavine wrote names eltavine as its copyright holder. A file somebody else wrote keeps its holder, and gets a
"Co-author: eltavine" line once eltavine has changed it; such a file without a header gets the upstream notice first.
"Wrote" means eltavine added the file and authors most of its code lines (imports and package lines do not count, since
copy detection credits them to whichever file had them first). Code moved into a new file stays with its original
author, and a file that came from upstream keeps the upstream notice however much of it eltavine rewrote.

Authorship comes from `git blame -w -M -C -C` with .git-blame-ignore-revs, so formatting, project-wide renames and
moves do not count. Vendored code under third_party/ keeps the notices of its own projects.

    python3 tools/update_attribution.py                 # rewrite the headers
    python3 tools/update_attribution.py --report        # print the classification without writing
    python3 tools/update_attribution.py PATH [PATH...]  # only these files, e.g. the ones a branch changes
"""

import argparse
import concurrent.futures
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
AUTHOR_EMAIL = "me@eltavine.com"
AUTHOR = f"eltavine <{AUTHOR_EMAIL}>"
# The holder upstream Zhihu++ names in every file it ships.
UPSTREAM_HOLDER = "Copyright (C) 2024-2026, zly2006 <i@zly2006.me>"
# Older files say "...client for Android."; both are the project notice, and rewriting a header normalizes it.
HEADER_MARK = "Zhihu-Hyperion - Free & Ad-Free Zhihu client for"
HEADER_TITLE = "Zhihu-Hyperion - Free & Ad-Free Zhihu client for all platforms."
IGNORE_REVS = ROOT / ".git-blame-ignore-revs"
# Files eltavine wrote without any header get the .copyright notice in their comment syntax.
COMMENT_STYLES = {
    ".kt": "block",
    ".kts": "block",
    ".swift": "block",
    ".py": "hash",
    ".sh": "hash",
    ".toml": "hash",
    ".yml": "hash",
    ".yaml": "hash",
}
# Front matter, shebangs and XML prologues can come before the header.
HEADER_SEARCH_LINES = 20
BOILERPLATE = ("import ", "package ", "from ")
OTHER_LICENSE = re.compile(r"copyright|licensed under|spdx-license-identifier", re.IGNORECASE)
EXCLUDED = (
    "third_party/",
    # Generated by core/icons/symbols.py from the header of AppIcon.kt.
    "core/icons/src/commonMain/kotlin/com/github/zly2006/zhihu/icons/AppIcons.kt",
)


def git(*args: str) -> str:
    return subprocess.run(["git", *args], cwd=ROOT, check=True, capture_output=True, text=True).stdout


def ignored_revs() -> set[str]:
    return {line.strip() for line in IGNORE_REVS.read_text(encoding="utf-8").splitlines() if line.strip() and not line.startswith("#")}


def header_end(lines: list[str]) -> int:
    """Index of the first line after the license header, or 0 when the file has none.

    The end comes from the comment syntax, not the license wording, which differs slightly between files.
    """
    mark = next((index for index, line in enumerate(lines[:HEADER_SEARCH_LINES]) if HEADER_MARK in line), None)
    if mark is None:
        return 0
    prefix = lines[mark][: lines[mark].index(HEADER_MARK)]
    for index in range(mark + 1, len(lines)):
        line = lines[index]
        marker = prefix.strip()
        if marker in ("#", "//"):
            if not line.startswith(marker):
                return index
        elif line.strip().endswith("*/") or line.strip().endswith("-->"):
            return index + 1
    return len(lines)


def blame_share(path: str, skip: int) -> tuple[int, int]:
    """(code lines eltavine authored, all code lines) after the license header, without imports and package lines."""
    output = git("blame", "--line-porcelain", "-w", "-M", "-C", "-C", "--ignore-revs-file", str(IGNORE_REVS), "HEAD", "--", path)
    mine = total = 0
    author_mail = ""
    line_number = 0
    for line in output.splitlines():
        if line.startswith("author-mail "):
            author_mail = line[len("author-mail "):].strip("<>")
        elif line.startswith("\t"):
            line_number += 1
            code = line[1:].strip()
            if line_number <= skip or not code or code.startswith(BOILERPLATE):
                continue
            total += 1
            mine += author_mail == AUTHOR_EMAIL
    return mine, total


def history(path: str, ignored: set[str]) -> tuple[str, list[str]]:
    """(email of the author who added the file, years in which eltavine changed its content).

    Mechanical commits and pure renames (R100) are not changes to the content.
    """
    commits = []
    # A small new file is mostly license header, so the default 50% would pair it with any file deleted alongside it.
    for line in git("log", "--follow", "-M90%", "--format=commit %H %ae %ad", "--date=format:%Y", "--name-status", "--", path).splitlines():
        if line.startswith("commit "):
            commits.append(line.split()[1:] + [""])
        elif line.strip() and commits:
            commits[-1][3] = line.split("\t")[0]
    if commits:
        creator = commits[-1][1]
    else:
        # A file added while resolving a merge has no non-merge commit that adds it.
        merges = git("log", "-m", "--diff-filter=A", "--format=%ae", "--", path).split()
        creator = merges[-1] if merges else ""
    years = sorted({year for sha, mail, year, status in commits if mail == AUTHOR_EMAIL and sha not in ignored and status != "R100"})
    return creator, years


def classify(path: str, ignored: set[str]) -> dict:
    # Blame reads the committed file, so the header it skips must be measured on the same content.
    lines = git("show", f"HEAD:{path}").splitlines()
    skip = header_end(lines)
    mine, total = blame_share(path, skip)
    creator, years = history(path, ignored)
    written = creator == AUTHOR_EMAIL and total > 0 and mine * 2 >= total
    if written:
        kind = "written"
    elif years or mine:
        kind = "co"
    else:
        kind = "none"
    # Code taken from other projects keeps its own notice (TwoRowsTopAppBar.kt is Apache-2.0 from AOSP).
    other_license = skip == 0 and OTHER_LICENSE.search("\n".join(lines[:30])) is not None
    return {
        "path": path,
        "kind": kind,
        "header": skip > 0,
        "other_license": other_license,
        "mine": mine,
        "total": total,
        "creator": creator,
        "years": years,
    }


def year_range(years: list[str]) -> str:
    return years[0] if years[0] == years[-1] else f"{years[0]}-{years[-1]}"


def rewrite_header(lines: list[str], kind: str, years: list[str]) -> list[str] | None:
    mark = next(index for index, line in enumerate(lines[:HEADER_SEARCH_LINES]) if HEADER_MARK in line)
    prefix = lines[mark][: lines[mark].index(HEADER_MARK)]
    end = mark + 1
    while end < len(lines) and (lines[end].startswith(prefix + "Copyright") or lines[end].startswith(prefix + "Co-author:")):
        end += 1
    others = [line for line in lines[mark + 1:end] if not line.startswith(prefix + "Co-author:") and AUTHOR_EMAIL not in line]
    if kind == "written":
        replacement = [f"{prefix}Copyright (C) {year_range(years or ['2026'])}, {AUTHOR}"]
    elif kind == "co":
        # A file that an earlier rule wrongly gave to eltavine gets the upstream holder back.
        replacement = (others or [f"{prefix}{UPSTREAM_HOLDER}"]) + [f"{prefix}Co-author: {AUTHOR}"]
    else:
        return None
    title = prefix + HEADER_TITLE
    if lines[mark] == title and lines[mark + 1:end] == replacement:
        return None
    return lines[:mark] + [title] + replacement + lines[end:]


def new_header(path: str, kind: str, years: list[str]) -> list[str] | None:
    style = COMMENT_STYLES.get(pathlib.Path(path).suffix)
    if style is None:
        return None
    template = (ROOT / ".copyright").read_text(encoding="utf-8").splitlines()
    holder = next(index for index, line in enumerate(template) if "Copyright (C)" in line)
    if kind == "written":
        template[holder:holder + 1] = [f" * Copyright (C) {year_range(years or ['2026'])}, {AUTHOR}"]
    else:
        template[holder:holder + 1] = [f" * {UPSTREAM_HOLDER}", f" * Co-author: {AUTHOR}"]
    if style == "block":
        return template
    # " * text" -> "# text"; drop the "/*" and " */" lines.
    return [("# " + line[3:]).rstrip() if line.startswith(" * ") else "#" for line in template[1:-1]]


def apply(result: dict) -> bool:
    path = ROOT / result["path"]
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
    # The file may already carry the header that an earlier run added, even though HEAD does not.
    if header_end(lines) > 0:
        updated = rewrite_header(lines, result["kind"], result["years"])
    elif result["kind"] != "none" and not result["other_license"]:
        header = new_header(result["path"], result["kind"], result["years"])
        if header is None:
            return False
        # Keep a shebang first, and leave a blank line between the header and the code.
        start = 1 if lines and lines[0].startswith("#!") else 0
        updated = lines[:start] + header + ([""] if lines[start:] and lines[start].strip() else []) + lines[start:]
    else:
        return False
    if updated is None:
        return False
    path.write_text("\n".join(updated) + ("\n" if text.endswith("\n") else ""), encoding="utf-8")
    return True


def candidates(only: list[str]) -> list[str]:
    files = []
    for path in only or git("ls-files").splitlines():
        if path.startswith(EXCLUDED) or not (ROOT / path).is_file():
            continue
        try:
            head = (ROOT / path).read_text(encoding="utf-8")[:2000]
        except UnicodeDecodeError:
            continue
        if HEADER_MARK in head or pathlib.Path(path).suffix in COMMENT_STYLES:
            files.append(path)
    return files


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--report", action="store_true", help="print the classification without writing files")
    parser.add_argument("paths", nargs="*", help="files to process instead of every tracked file")
    args = parser.parse_args()

    ignored = ignored_revs()
    paths = candidates(args.paths)
    with concurrent.futures.ThreadPoolExecutor(max_workers=8) as pool:
        results = list(pool.map(lambda path: classify(path, ignored), paths))

    changed = 0
    for result in sorted(results, key=lambda r: r["path"]):
        if args.report:
            if result["kind"] != "none" or not result["header"]:
                share = f"{result['mine']}/{result['total']}"
                print(f"{result['kind']:8} {'header' if result['header'] else 'none  '} {share:>11}  {result['path']}")
        elif apply(result):
            changed += 1
    if not args.report:
        print(f"Updated {changed} of {len(results)} files.", file=sys.stderr)


if __name__ == "__main__":
    main()
